# Generated by Django 5.0 on 2025-11-03 22:01

import django.core.validators
import django.db.models.deletion
import pgvector.django
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="E.g., 'Highlights Tour', 'Complete Exhibition'", max_length=255)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField(help_text='Estimated tour duration')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy - Wheelchair Accessible'), ('moderate', 'Moderate - Some stairs'), ('challenging', 'Challenging - Multiple floors')], default='easy', max_length=20)),
                ('waypoint_sequence', models.JSONField(default=list, help_text='Ordered list of waypoint UUIDs')),
                ('total_distance_meters', models.FloatField(default=0)),
                ('artwork_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('avg_completion_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_paths', to='core.museum')),
            ],
            options={
                'ordering': ['-is_featured', '-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='NavigationWaypoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('floor_level', models.IntegerField(default=1, help_text='Floor number (1=Ground, 2=First, etc.)')),
                ('room_name', models.CharField(blank=True, help_text="E.g., 'Renaissance Gallery'", max_length=100)),
                ('video_360', models.FileField(help_text='360° video captured at this location for visual matching', upload_to='navigation/waypoints/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])])),
                ('thumbnail', models.ImageField(blank=True, help_text='Preview image extracted from 360° video', null=True, upload_to='navigation/thumbnails/')),
                ('title', models.CharField(help_text="E.g., 'Entrance Hall', 'Gallery Intersection'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Landmarks or directions visible from here')),
                ('voice_instruction', models.TextField(blank=True, help_text="Text for TTS: 'Walk 20 steps forward...'")),
                ('sequence_order', models.IntegerField(default=0, help_text='Order in the navigation path')),
                ('distance_to_next_meters', models.FloatField(blank=True, help_text='Distance to next waypoint in meters', null=True)),
                ('estimated_walk_seconds', models.IntegerField(blank=True, help_text='Estimated time to walk to next waypoint', null=True)),
                ('position_embedding', pgvector.django.VectorField(blank=True, dimensions=512, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork', models.ForeignKey(blank=True, help_text='Artwork located at this waypoint (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waypoints', to='core.artwork')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_waypoints', to=settings.AUTH_USER_MODEL)),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='core.museum')),
                ('next_waypoint', models.ForeignKey(blank=True, help_text='Next step in the navigation sequence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_waypoint', to='core.navigationwaypoint')),
            ],
            options={
                'ordering': ['museum', 'floor_level', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='VisitorNavigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visited_waypoints', models.JSONField(default=list, help_text='List of visited waypoint UUIDs with timestamps')),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_waypoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_visitors', to='core.navigationwaypoint')),
                ('path', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_sessions', to='core.navigationpath')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_sessions', to='core.visitorsession')),
                ('target_artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_targets', to='core.artwork')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='navigationpath',
            index=models.Index(fields=['museum', 'is_active'], name='core_naviga_museum__867e39_idx'),
        ),
        migrations.AddIndex(
            model_name='navigationwaypoint',
            index=models.Index(fields=['museum', 'floor_level', 'is_active'], name='core_naviga_museum__c5d340_idx'),
        ),
        migrations.AddIndex(
            model_name='navigationwaypoint',
            index=models.Index(fields=['sequence_order'], name='core_naviga_sequenc_718ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='navigationwaypoint',
            index=models.Index(fields=['artwork'], name='core_naviga_artwork_aa9478_idx'),
        ),
        migrations.AddIndex(
            model_name='visitornavigation',
            index=models.Index(fields=['session', 'status'], name='core_visito_session_0efe00_idx'),
        ),
    ]
