# Generated by Django 5.0 on 2025-11-04 02:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_navigationpath_navigationwaypoint_visitornavigation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('floor_level', models.IntegerField(help_text='Floor number (1=Ground, 2=First floor, 0=Basement, etc.)')),
                ('floor_name', models.CharField(help_text="Display name (e.g., 'Ground Floor', 'Renaissance Gallery')", max_length=100)),
                ('floor_plan_image', models.ImageField(help_text='Upload floor plan image (PNG, JPG recommended)', upload_to='museum/floor_maps/')),
                ('image_width', models.IntegerField(default=1000, help_text='Floor plan image width in pixels')),
                ('image_height', models.IntegerField(default=1000, help_text='Floor plan image height in pixels')),
                ('real_width_meters', models.FloatField(blank=True, help_text='Actual floor width in meters (for scale calculation)', null=True)),
                ('real_height_meters', models.FloatField(blank=True, help_text='Actual floor height in meters (for scale calculation)', null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Display order in floor selector (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_floor_maps', to=settings.AUTH_USER_MODEL)),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_maps', to='core.museum')),
            ],
            options={
                'ordering': ['museum', 'floor_level'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkMapPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x_position', models.IntegerField(help_text='X coordinate on floor plan image (pixels from left)')),
                ('y_position', models.IntegerField(help_text='Y coordinate on floor plan image (pixels from top)')),
                ('rotation_degrees', models.IntegerField(default=0, help_text='Icon rotation (0-360 degrees)')),
                ('pin_color', models.CharField(default='#D4AF37', help_text='Pin color in hex (default: gold)', max_length=7)),
                ('pin_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_position', to='core.artwork')),
                ('floor_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_positions', to='core.floormap')),
            ],
            options={
                'ordering': ['floor_map', 'artwork'],
            },
        ),
        migrations.AddIndex(
            model_name='floormap',
            index=models.Index(fields=['museum', 'is_active'], name='core_floorm_museum__237d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='floormap',
            index=models.Index(fields=['floor_level'], name='core_floorm_floor_l_0a567f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='floormap',
            unique_together={('museum', 'floor_level')},
        ),
        migrations.AddIndex(
            model_name='artworkmapposition',
            index=models.Index(fields=['floor_map', 'is_visible'], name='core_artwor_floor_m_48ad08_idx'),
        ),
        migrations.AddIndex(
            model_name='artworkmapposition',
            index=models.Index(fields=['artwork'], name='core_artwor_artwork_b29153_idx'),
        ),
    ]
